/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.shop.by.diagram.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CPDefinitionDiagramSettings service. Represents a row in the &quot;CPDefinitionDiagramSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.shop.by.diagram.model.impl.CPDefinitionDiagramSettingsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.shop.by.diagram.model.impl.CPDefinitionDiagramSettingsImpl</code>.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CPDefinitionDiagramSettings
 * @generated
 */
@ProviderType
public interface CPDefinitionDiagramSettingsModel
	extends AuditedModel, BaseModel<CPDefinitionDiagramSettings>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cp definition diagram settings model instance should use the {@link CPDefinitionDiagramSettings} interface instead.
	 */

	/**
	 * Returns the primary key of this cp definition diagram settings.
	 *
	 * @return the primary key of this cp definition diagram settings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cp definition diagram settings.
	 *
	 * @param primaryKey the primary key of this cp definition diagram settings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cp definition diagram settings ID of this cp definition diagram settings.
	 *
	 * @return the cp definition diagram settings ID of this cp definition diagram settings
	 */
	public long getCPDefinitionDiagramSettingsId();

	/**
	 * Sets the cp definition diagram settings ID of this cp definition diagram settings.
	 *
	 * @param CPDefinitionDiagramSettingsId the cp definition diagram settings ID of this cp definition diagram settings
	 */
	public void setCPDefinitionDiagramSettingsId(
		long CPDefinitionDiagramSettingsId);

	/**
	 * Returns the company ID of this cp definition diagram settings.
	 *
	 * @return the company ID of this cp definition diagram settings
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cp definition diagram settings.
	 *
	 * @param companyId the company ID of this cp definition diagram settings
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cp definition diagram settings.
	 *
	 * @return the user ID of this cp definition diagram settings
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cp definition diagram settings.
	 *
	 * @param userId the user ID of this cp definition diagram settings
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cp definition diagram settings.
	 *
	 * @return the user uuid of this cp definition diagram settings
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cp definition diagram settings.
	 *
	 * @param userUuid the user uuid of this cp definition diagram settings
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cp definition diagram settings.
	 *
	 * @return the user name of this cp definition diagram settings
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cp definition diagram settings.
	 *
	 * @param userName the user name of this cp definition diagram settings
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cp definition diagram settings.
	 *
	 * @return the create date of this cp definition diagram settings
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cp definition diagram settings.
	 *
	 * @param createDate the create date of this cp definition diagram settings
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cp definition diagram settings.
	 *
	 * @return the modified date of this cp definition diagram settings
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cp definition diagram settings.
	 *
	 * @param modifiedDate the modified date of this cp definition diagram settings
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the cp definition ID of this cp definition diagram settings.
	 *
	 * @return the cp definition ID of this cp definition diagram settings
	 */
	public long getCPDefinitionId();

	/**
	 * Sets the cp definition ID of this cp definition diagram settings.
	 *
	 * @param CPDefinitionId the cp definition ID of this cp definition diagram settings
	 */
	public void setCPDefinitionId(long CPDefinitionId);

	/**
	 * Returns the asset category ID of this cp definition diagram settings.
	 *
	 * @return the asset category ID of this cp definition diagram settings
	 */
	public long getAssetCategoryId();

	/**
	 * Sets the asset category ID of this cp definition diagram settings.
	 *
	 * @param assetCategoryId the asset category ID of this cp definition diagram settings
	 */
	public void setAssetCategoryId(long assetCategoryId);

	/**
	 * Returns the name of this cp definition diagram settings.
	 *
	 * @return the name of this cp definition diagram settings
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cp definition diagram settings.
	 *
	 * @param name the name of this cp definition diagram settings
	 */
	public void setName(String name);

}