/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.shop.by.diagram.model.impl;

import com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramSettings;
import com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramSettingsLocalServiceUtil;

/**
 * The extended model base implementation for the CPDefinitionDiagramSettings service. Represents a row in the &quot;CPDefinitionDiagramSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPDefinitionDiagramSettingsImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CPDefinitionDiagramSettingsImpl
 * @see CPDefinitionDiagramSettings
 * @generated
 */
public abstract class CPDefinitionDiagramSettingsBaseImpl
	extends CPDefinitionDiagramSettingsModelImpl
	implements CPDefinitionDiagramSettings {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp definition diagram settings model instance should use the <code>CPDefinitionDiagramSettings</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CPDefinitionDiagramSettingsLocalServiceUtil.
				addCPDefinitionDiagramSettings(this);
		}
		else {
			CPDefinitionDiagramSettingsLocalServiceUtil.
				updateCPDefinitionDiagramSettings(this);
		}
	}

}