/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPSOListTypeDefinitionRel;
import com.liferay.commerce.product.model.CPSOListTypeDefinitionRelModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CPSOListTypeDefinitionRel service. Represents a row in the &quot;CPSOListTypeDefinitionRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CPSOListTypeDefinitionRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPSOListTypeDefinitionRelImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPSOListTypeDefinitionRelImpl
 * @generated
 */
@JSON(strict = true)
public class CPSOListTypeDefinitionRelModelImpl
	extends BaseModelImpl<CPSOListTypeDefinitionRel>
	implements CPSOListTypeDefinitionRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cpso list type definition rel model instance should use the <code>CPSOListTypeDefinitionRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPSOListTypeDefinitionRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"CPSOListTypeDefinitionRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"CPSpecificationOptionId", Types.BIGINT},
		{"listTypeDefinitionId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CPSOListTypeDefinitionRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CPSpecificationOptionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("listTypeDefinitionId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPSOListTypeDefinitionRel (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,CPSOListTypeDefinitionRelId LONG not null,companyId LONG,CPSpecificationOptionId LONG,listTypeDefinitionId LONG,primary key (CPSOListTypeDefinitionRelId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table CPSOListTypeDefinitionRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cpsoListTypeDefinitionRel.CPSOListTypeDefinitionRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPSOListTypeDefinitionRel.CPSOListTypeDefinitionRelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CPSPECIFICATIONOPTIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LISTTYPEDEFINITIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CPSOLISTTYPEDEFINITIONRELID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CPSOListTypeDefinitionRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPSOListTypeDefinitionRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPSOListTypeDefinitionRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPSOListTypeDefinitionRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPSOListTypeDefinitionRel.class;
	}

	@Override
	public String getModelClassName() {
		return CPSOListTypeDefinitionRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CPSOListTypeDefinitionRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CPSOListTypeDefinitionRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPSOListTypeDefinitionRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CPSOListTypeDefinitionRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CPSOListTypeDefinitionRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CPSOListTypeDefinitionRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CPSOListTypeDefinitionRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CPSOListTypeDefinitionRel, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CPSOListTypeDefinitionRel, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CPSOListTypeDefinitionRel, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CPSOListTypeDefinitionRel, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CPSOListTypeDefinitionRel, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CPSOListTypeDefinitionRel::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", CPSOListTypeDefinitionRel::getCtCollectionId);
			attributeGetterFunctions.put(
				"CPSOListTypeDefinitionRelId",
				CPSOListTypeDefinitionRel::getCPSOListTypeDefinitionRelId);
			attributeGetterFunctions.put(
				"companyId", CPSOListTypeDefinitionRel::getCompanyId);
			attributeGetterFunctions.put(
				"CPSpecificationOptionId",
				CPSOListTypeDefinitionRel::getCPSpecificationOptionId);
			attributeGetterFunctions.put(
				"listTypeDefinitionId",
				CPSOListTypeDefinitionRel::getListTypeDefinitionId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CPSOListTypeDefinitionRel, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CPSOListTypeDefinitionRel, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CPSOListTypeDefinitionRel, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CPSOListTypeDefinitionRel, Long>)
					CPSOListTypeDefinitionRel::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<CPSOListTypeDefinitionRel, Long>)
					CPSOListTypeDefinitionRel::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"CPSOListTypeDefinitionRelId",
				(BiConsumer<CPSOListTypeDefinitionRel, Long>)
					CPSOListTypeDefinitionRel::setCPSOListTypeDefinitionRelId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CPSOListTypeDefinitionRel, Long>)
					CPSOListTypeDefinitionRel::setCompanyId);
			attributeSetterBiConsumers.put(
				"CPSpecificationOptionId",
				(BiConsumer<CPSOListTypeDefinitionRel, Long>)
					CPSOListTypeDefinitionRel::setCPSpecificationOptionId);
			attributeSetterBiConsumers.put(
				"listTypeDefinitionId",
				(BiConsumer<CPSOListTypeDefinitionRel, Long>)
					CPSOListTypeDefinitionRel::setListTypeDefinitionId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public long getCPSOListTypeDefinitionRelId() {
		return _CPSOListTypeDefinitionRelId;
	}

	@Override
	public void setCPSOListTypeDefinitionRelId(
		long CPSOListTypeDefinitionRelId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPSOListTypeDefinitionRelId = CPSOListTypeDefinitionRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCPSpecificationOptionId() {
		return _CPSpecificationOptionId;
	}

	@Override
	public void setCPSpecificationOptionId(long CPSpecificationOptionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPSpecificationOptionId = CPSpecificationOptionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCPSpecificationOptionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("CPSpecificationOptionId"));
	}

	@JSON
	@Override
	public long getListTypeDefinitionId() {
		return _listTypeDefinitionId;
	}

	@Override
	public void setListTypeDefinitionId(long listTypeDefinitionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_listTypeDefinitionId = listTypeDefinitionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalListTypeDefinitionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("listTypeDefinitionId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CPSOListTypeDefinitionRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPSOListTypeDefinitionRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CPSOListTypeDefinitionRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPSOListTypeDefinitionRelImpl cpsoListTypeDefinitionRelImpl =
			new CPSOListTypeDefinitionRelImpl();

		cpsoListTypeDefinitionRelImpl.setMvccVersion(getMvccVersion());
		cpsoListTypeDefinitionRelImpl.setCtCollectionId(getCtCollectionId());
		cpsoListTypeDefinitionRelImpl.setCPSOListTypeDefinitionRelId(
			getCPSOListTypeDefinitionRelId());
		cpsoListTypeDefinitionRelImpl.setCompanyId(getCompanyId());
		cpsoListTypeDefinitionRelImpl.setCPSpecificationOptionId(
			getCPSpecificationOptionId());
		cpsoListTypeDefinitionRelImpl.setListTypeDefinitionId(
			getListTypeDefinitionId());

		cpsoListTypeDefinitionRelImpl.resetOriginalValues();

		return cpsoListTypeDefinitionRelImpl;
	}

	@Override
	public CPSOListTypeDefinitionRel cloneWithOriginalValues() {
		CPSOListTypeDefinitionRelImpl cpsoListTypeDefinitionRelImpl =
			new CPSOListTypeDefinitionRelImpl();

		cpsoListTypeDefinitionRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		cpsoListTypeDefinitionRelImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		cpsoListTypeDefinitionRelImpl.setCPSOListTypeDefinitionRelId(
			this.<Long>getColumnOriginalValue("CPSOListTypeDefinitionRelId"));
		cpsoListTypeDefinitionRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cpsoListTypeDefinitionRelImpl.setCPSpecificationOptionId(
			this.<Long>getColumnOriginalValue("CPSpecificationOptionId"));
		cpsoListTypeDefinitionRelImpl.setListTypeDefinitionId(
			this.<Long>getColumnOriginalValue("listTypeDefinitionId"));

		return cpsoListTypeDefinitionRelImpl;
	}

	@Override
	public int compareTo(CPSOListTypeDefinitionRel cpsoListTypeDefinitionRel) {
		long primaryKey = cpsoListTypeDefinitionRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CPSOListTypeDefinitionRel)) {
			return false;
		}

		CPSOListTypeDefinitionRel cpsoListTypeDefinitionRel =
			(CPSOListTypeDefinitionRel)object;

		long primaryKey = cpsoListTypeDefinitionRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CPSOListTypeDefinitionRel> toCacheModel() {
		CPSOListTypeDefinitionRelCacheModel
			cpsoListTypeDefinitionRelCacheModel =
				new CPSOListTypeDefinitionRelCacheModel();

		cpsoListTypeDefinitionRelCacheModel.mvccVersion = getMvccVersion();

		cpsoListTypeDefinitionRelCacheModel.ctCollectionId =
			getCtCollectionId();

		cpsoListTypeDefinitionRelCacheModel.CPSOListTypeDefinitionRelId =
			getCPSOListTypeDefinitionRelId();

		cpsoListTypeDefinitionRelCacheModel.companyId = getCompanyId();

		cpsoListTypeDefinitionRelCacheModel.CPSpecificationOptionId =
			getCPSpecificationOptionId();

		cpsoListTypeDefinitionRelCacheModel.listTypeDefinitionId =
			getListTypeDefinitionId();

		return cpsoListTypeDefinitionRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CPSOListTypeDefinitionRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CPSOListTypeDefinitionRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPSOListTypeDefinitionRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CPSOListTypeDefinitionRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CPSOListTypeDefinitionRel>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CPSOListTypeDefinitionRel.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _CPSOListTypeDefinitionRelId;
	private long _companyId;
	private long _CPSpecificationOptionId;
	private long _listTypeDefinitionId;

	public <T> T getColumnValue(String columnName) {
		Function<CPSOListTypeDefinitionRel, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CPSOListTypeDefinitionRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put(
			"CPSOListTypeDefinitionRelId", _CPSOListTypeDefinitionRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put(
			"CPSpecificationOptionId", _CPSpecificationOptionId);
		_columnOriginalValues.put(
			"listTypeDefinitionId", _listTypeDefinitionId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("CPSOListTypeDefinitionRelId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("CPSpecificationOptionId", 16L);

		columnBitmasks.put("listTypeDefinitionId", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CPSOListTypeDefinitionRel _escapedModel;

}