apiDir: ../headless-cms-api/src/main/java
apiPackagePath: com.liferay.headless.cms
application:
    baseURI: /headless-cms
    className: HeadlessCmsApplication
    name: Liferay.Headless.Cms
author: Crescenzo Rega
changeTrackingEnabled: true
clientDir: ../headless-cms-client/src/main/java
compatibilityVersion: 11
forcePredictableOperationId: true
generatePermissions: true
javaEEPackage: jakarta
testDir: ../headless-cms-test/src/testIntegration/java