components:
    schemas:
        BulkActionDefinition:
            discriminator:
                mapping:
                    Category: "#/components/schemas/CategoryDefinition"
                    Move: "#/components/schemas/MoveDefinition"
                    Permission: "#/components/schemas/PermissionDefinition"
                    Status: "#/components/schemas/StatusDefinition"
                    Tag: "#/components/schemas/TagDefinition"
                propertyName: type
            properties:
                cmsEntryDefinitions:
                    items:
                        $ref: "#/components/schemas/CMSEntryDefinition"
                    type: array
                type:
                    enum:
                        -   Category
                        -   Move
                        -   Permission
                        -   Status
                        -   Tag
                    type: string
        BulkActionTask:
            properties:
                bulkActionTaskId:
                    description:
                        The bulk action task ID.
                    format: int64
                    type: integer
        CMSEntryDefinition:
            properties:
                className:
                    type: string
                id:
                    format: int64
                    type: integer
        CategoryDefinition:
            allOf:
                -   $ref: "#/components/schemas/BulkActionDefinition"
                -   properties:
                        taxonomyCategoryIds:
                            items:
                                format: int64
                                type: integer
                            type: array
        MoveDefinition:
            allOf:
                -   $ref: "#/components/schemas/BulkActionDefinition"
                -   properties:
                        objectEntryFolderId:
                            description:
                                The object entry folder's ID.
                            format: int64
                            type: integer
        PermissionDefinition:
            allOf:
                -   $ref: "#/components/schemas/BulkActionDefinition"
                -   properties:
                        permissions:
                            items:
                                type: permission
                            type: array
        StatusDefinition:
            allOf:
                -   $ref: "#/components/schemas/BulkActionDefinition"
                -   properties:
                        status:
                            format: int32
                            type: integer
        TagDefinition:
            allOf:
                -   $ref: "#/components/schemas/BulkActionDefinition"
                -   properties:
                        keywords:
                            items:
                                type: string
                            type: array
info:
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/bulk-action":
        delete:
            description:
                Execute the bulk remove change action.
            parameters:
                -   in: query
                    name: filter
                    required: false
                    schema:
                        type: string
                -   in: query
                    name: search
                    required: false
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            items:
                                $ref: "#/components/schemas/CMSEntryDefinition"
                            type: array
                    application/xml:
                        schema:
                            items:
                                $ref: "#/components/schemas/CMSEntryDefinition"
                            type: array
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
            tags: ["BulkAction"]
    "/bulk-action/categories":
        post:
            description:
                Execute the bulk category change action
            parameters:
                -   in: query
                    name: filter
                    required: false
                    schema:
                        type: string
                -   in: query
                    name: search
                    required: false
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CategoryDefinition"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CategoryDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
            tags: ["BulkAction"]
    "/bulk-action/move":
        post:
            description:
                Execute the bulk move change action.
            parameters:
                -   in: query
                    name: filter
                    required: false
                    schema:
                        type: string
                -   in: query
                    name: search
                    required: false
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/MoveDefinition"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/MoveDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
            tags: ["BulkAction"]
    "/bulk-action/permissions":
        post:
            description:
                Execute the bulk permission change action.
            parameters:
                -   in: query
                    name: filter
                    required: false
                    schema:
                        type: string
                -   in: query
                    name: search
                    required: false
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PermissionDefinition"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/PermissionDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
            tags: ["BulkAction"]
    "/bulk-action/status":
        post:
            description:
                Execute the bulk status change action
            parameters:
                -   in: query
                    name: filter
                    required: false
                    schema:
                        type: string
                -   in: query
                    name: search
                    required: false
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/StatusDefinition"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/StatusDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
            tags: ["BulkAction"]
    "/bulk-action/tags":
        post:
            description:
                Execute the bulk tag change action
            parameters:
                -   in: query
                    name: filter
                    required: false
                    schema:
                        type: string
                -   in: query
                    name: search
                    required: false
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/TagDefinition"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/TagDefinition"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/BulkActionTask"
            tags: ["BulkAction"]