/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceRegionLocalization service. Represents a row in the &quot;CommerceRegionLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.model.impl.CommerceRegionLocalizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.model.impl.CommerceRegionLocalizationImpl</code>.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceRegionLocalization
 * @generated
 */
@ProviderType
public interface CommerceRegionLocalizationModel
	extends BaseModel<CommerceRegionLocalization>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce region localization model instance should use the {@link CommerceRegionLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce region localization.
	 *
	 * @return the primary key of this commerce region localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce region localization.
	 *
	 * @param primaryKey the primary key of this commerce region localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce region localization.
	 *
	 * @return the mvcc version of this commerce region localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce region localization.
	 *
	 * @param mvccVersion the mvcc version of this commerce region localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the commerce region localization ID of this commerce region localization.
	 *
	 * @return the commerce region localization ID of this commerce region localization
	 */
	public long getCommerceRegionLocalizationId();

	/**
	 * Sets the commerce region localization ID of this commerce region localization.
	 *
	 * @param commerceRegionLocalizationId the commerce region localization ID of this commerce region localization
	 */
	public void setCommerceRegionLocalizationId(
		long commerceRegionLocalizationId);

	/**
	 * Returns the company ID of this commerce region localization.
	 *
	 * @return the company ID of this commerce region localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce region localization.
	 *
	 * @param companyId the company ID of this commerce region localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the commerce region ID of this commerce region localization.
	 *
	 * @return the commerce region ID of this commerce region localization
	 */
	public long getCommerceRegionId();

	/**
	 * Sets the commerce region ID of this commerce region localization.
	 *
	 * @param commerceRegionId the commerce region ID of this commerce region localization
	 */
	public void setCommerceRegionId(long commerceRegionId);

	/**
	 * Returns the language ID of this commerce region localization.
	 *
	 * @return the language ID of this commerce region localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this commerce region localization.
	 *
	 * @param languageId the language ID of this commerce region localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the name of this commerce region localization.
	 *
	 * @return the name of this commerce region localization
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this commerce region localization.
	 *
	 * @param name the name of this commerce region localization
	 */
	public void setName(String name);

}