#
# Application
#

liferay.learn.dxp.site.group.id=
liferay.learn.google.credentials=
liferay.learn.webassessor.security.token=
liferay.learn.jira.api.email.address=${LIFERAY_LEARN_JIRA_API_EMAIL_ADDRESS}
liferay.learn.jira.api.token=${LIFERAY_LEARN_JIRA_API_TOKEN}
liferay.learn.jira.security.vulnerability.field.affected.versions.details=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_AFFECTED_VERSIONS_DETAILS}
liferay.learn.jira.security.vulnerability.field.affects=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_AFFECTS}
liferay.learn.jira.security.vulnerability.field.categories=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CATEGORIES}
liferay.learn.jira.security.vulnerability.field.customer.portal.description=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PORTAL_DESCRIPTION}
liferay.learn.jira.security.vulnerability.field.customer.portal.summary=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PORTAL_SUMMARY}
liferay.learn.jira.security.vulnerability.field.customer.publishing.date=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CUSTOMER_PUBLISHING_DATE}
liferay.learn.jira.security.vulnerability.field.cve.ids=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CVE_IDS}
liferay.learn.jira.security.vulnerability.field.cvss.base.score=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CVSS_BASE_SCORE}
liferay.learn.jira.security.vulnerability.field.cvss.vector.string=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CVSS_VECTOR_STRING}
liferay.learn.jira.security.vulnerability.field.cwe.ids=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_CWE_IDS}
liferay.learn.jira.security.vulnerability.field.fix.versions=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_FIX_VERSIONS}
liferay.learn.jira.security.vulnerability.field.issue.classification=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_ISSUE_CLASSIFICATION}
liferay.learn.jira.security.vulnerability.field.partner.publishing.date=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_PARTNER_PUBLISHING_DATE}
liferay.learn.jira.security.vulnerability.field.publishing.status=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_PUBLISHING_STATUS}
liferay.learn.jira.security.vulnerability.field.severity=${LIFERAY_LEARN_JIRA_SECURITY_VULNERABILITY_FIELD_SEVERITY}
liferay.learn.jira.security.vulnerability.project=LSV
liferay.learn.jira.support.hc.field.organization=${LIFERAY_LEARN_JIRA_SUPPORT_HC_FIELD_ORGANIZATION}
liferay.learn.jira.url=${LIFERAY_LEARN_JIRA_URL}

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-learn-etc-spring-boot-oahs.oauth2.headless.server.client.secret=myfancypassword

liferay.oauth.application.external.reference.codes=\
    liferay-learn-etc-spring-boot-oahs,\
    liferay-learn-etc-spring-boot-oaua

liferay.oauth.urls.excludes=\
    /learn/*\/questions,\
    /learn/*\/result,\
    /learn/lesson/*\/audio/base64,\
    /rag/search,\
    /ready

#
# Spring Boot
#

server.port=58081