buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
	}

	repositories {
		maven {
			url new File(rootProject.projectDir, "../../.m2-tmp")
		}

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "application"
apply plugin: "com.liferay.source.formatter"
apply plugin: "java-library"

task fatJar(type: Jar)

dependencies {
	implementation group: "com.liferay", name: "com.liferay.petra.string", version: "latest.release"
	implementation group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "latest.release"
	implementation group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.13"
	implementation group: "org.json", name: "json", version: "20231013"
}

fatJar {
	archiveBaseName = project.name + "-all"
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	excludes = ["META-INF/*.DSA", "META-INF/*.RSA", "META-INF/*.SF"]

	from {
		configurations.runtimeClasspath.collect {
			it.isDirectory() ? it : zipTree(it)
		}
	}

	manifest {
		attributes "Main-Class": "com.liferay.learn.Main"
	}

	with jar
}

mainClassName = "com.liferay.learn.Main"

repositories {
	maven {
		url new File(rootProject.projectDir, "../../.m2-tmp")
	}

	maven {
		url "https://repository-cdn.liferay.com/nexus/content/groups/public"
	}
}