/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.shop.by.diagram.service.base;

import com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramSettings;
import com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramSettingsLocalService;
import com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramSettingsLocalServiceUtil;
import com.liferay.commerce.shop.by.diagram.service.persistence.CPDefinitionDiagramEntryPersistence;
import com.liferay.commerce.shop.by.diagram.service.persistence.CPDefinitionDiagramSettingsPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the cp definition diagram settings local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.shop.by.diagram.service.impl.CPDefinitionDiagramSettingsLocalServiceImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see com.liferay.commerce.shop.by.diagram.service.impl.CPDefinitionDiagramSettingsLocalServiceImpl
 * @generated
 */
public abstract class CPDefinitionDiagramSettingsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements CPDefinitionDiagramSettingsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CPDefinitionDiagramSettingsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CPDefinitionDiagramSettingsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cp definition diagram settings to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPDefinitionDiagramSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpDefinitionDiagramSettings the cp definition diagram settings
	 * @return the cp definition diagram settings that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CPDefinitionDiagramSettings addCPDefinitionDiagramSettings(
		CPDefinitionDiagramSettings cpDefinitionDiagramSettings) {

		cpDefinitionDiagramSettings.setNew(true);

		return cpDefinitionDiagramSettingsPersistence.update(
			cpDefinitionDiagramSettings);
	}

	/**
	 * Creates a new cp definition diagram settings with the primary key. Does not add the cp definition diagram settings to the database.
	 *
	 * @param CPDefinitionDiagramSettingsId the primary key for the new cp definition diagram settings
	 * @return the new cp definition diagram settings
	 */
	@Override
	@Transactional(enabled = false)
	public CPDefinitionDiagramSettings createCPDefinitionDiagramSettings(
		long CPDefinitionDiagramSettingsId) {

		return cpDefinitionDiagramSettingsPersistence.create(
			CPDefinitionDiagramSettingsId);
	}

	/**
	 * Deletes the cp definition diagram settings with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPDefinitionDiagramSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param CPDefinitionDiagramSettingsId the primary key of the cp definition diagram settings
	 * @return the cp definition diagram settings that was removed
	 * @throws PortalException if a cp definition diagram settings with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CPDefinitionDiagramSettings deleteCPDefinitionDiagramSettings(
			long CPDefinitionDiagramSettingsId)
		throws PortalException {

		return cpDefinitionDiagramSettingsPersistence.remove(
			CPDefinitionDiagramSettingsId);
	}

	/**
	 * Deletes the cp definition diagram settings from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPDefinitionDiagramSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpDefinitionDiagramSettings the cp definition diagram settings
	 * @return the cp definition diagram settings that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CPDefinitionDiagramSettings deleteCPDefinitionDiagramSettings(
		CPDefinitionDiagramSettings cpDefinitionDiagramSettings) {

		return cpDefinitionDiagramSettingsPersistence.remove(
			cpDefinitionDiagramSettings);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return cpDefinitionDiagramSettingsPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CPDefinitionDiagramSettings.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return cpDefinitionDiagramSettingsPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.shop.by.diagram.model.impl.CPDefinitionDiagramSettingsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return cpDefinitionDiagramSettingsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.shop.by.diagram.model.impl.CPDefinitionDiagramSettingsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return cpDefinitionDiagramSettingsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return cpDefinitionDiagramSettingsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return cpDefinitionDiagramSettingsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CPDefinitionDiagramSettings fetchCPDefinitionDiagramSettings(
		long CPDefinitionDiagramSettingsId) {

		return cpDefinitionDiagramSettingsPersistence.fetchByPrimaryKey(
			CPDefinitionDiagramSettingsId);
	}

	/**
	 * Returns the cp definition diagram settings with the primary key.
	 *
	 * @param CPDefinitionDiagramSettingsId the primary key of the cp definition diagram settings
	 * @return the cp definition diagram settings
	 * @throws PortalException if a cp definition diagram settings with the primary key could not be found
	 */
	@Override
	public CPDefinitionDiagramSettings getCPDefinitionDiagramSettings(
			long CPDefinitionDiagramSettingsId)
		throws PortalException {

		return cpDefinitionDiagramSettingsPersistence.findByPrimaryKey(
			CPDefinitionDiagramSettingsId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			cpDefinitionDiagramSettingsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CPDefinitionDiagramSettings.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPDefinitionDiagramSettingsId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			cpDefinitionDiagramSettingsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CPDefinitionDiagramSettings.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPDefinitionDiagramSettingsId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			cpDefinitionDiagramSettingsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CPDefinitionDiagramSettings.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"CPDefinitionDiagramSettingsId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cpDefinitionDiagramSettingsPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return cpDefinitionDiagramSettingsLocalService.
			deleteCPDefinitionDiagramSettings(
				(CPDefinitionDiagramSettings)persistedModel);
	}

	@Override
	public BasePersistence<CPDefinitionDiagramSettings> getBasePersistence() {
		return cpDefinitionDiagramSettingsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cpDefinitionDiagramSettingsPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the cp definition diagram settingses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.shop.by.diagram.model.impl.CPDefinitionDiagramSettingsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cp definition diagram settingses
	 * @param end the upper bound of the range of cp definition diagram settingses (not inclusive)
	 * @return the range of cp definition diagram settingses
	 */
	@Override
	public List<CPDefinitionDiagramSettings> getCPDefinitionDiagramSettingses(
		int start, int end) {

		return cpDefinitionDiagramSettingsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cp definition diagram settingses.
	 *
	 * @return the number of cp definition diagram settingses
	 */
	@Override
	public int getCPDefinitionDiagramSettingsesCount() {
		return cpDefinitionDiagramSettingsPersistence.countAll();
	}

	/**
	 * Updates the cp definition diagram settings in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CPDefinitionDiagramSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cpDefinitionDiagramSettings the cp definition diagram settings
	 * @return the cp definition diagram settings that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CPDefinitionDiagramSettings updateCPDefinitionDiagramSettings(
		CPDefinitionDiagramSettings cpDefinitionDiagramSettings) {

		return cpDefinitionDiagramSettingsPersistence.update(
			cpDefinitionDiagramSettings);
	}

	/**
	 * Returns the cp definition diagram entry local service.
	 *
	 * @return the cp definition diagram entry local service
	 */
	public com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramEntryLocalService
			getCPDefinitionDiagramEntryLocalService() {

		return cpDefinitionDiagramEntryLocalService;
	}

	/**
	 * Sets the cp definition diagram entry local service.
	 *
	 * @param cpDefinitionDiagramEntryLocalService the cp definition diagram entry local service
	 */
	public void setCPDefinitionDiagramEntryLocalService(
		com.liferay.commerce.shop.by.diagram.service.
			CPDefinitionDiagramEntryLocalService
				cpDefinitionDiagramEntryLocalService) {

		this.cpDefinitionDiagramEntryLocalService =
			cpDefinitionDiagramEntryLocalService;
	}

	/**
	 * Returns the cp definition diagram entry persistence.
	 *
	 * @return the cp definition diagram entry persistence
	 */
	public CPDefinitionDiagramEntryPersistence
		getCPDefinitionDiagramEntryPersistence() {

		return cpDefinitionDiagramEntryPersistence;
	}

	/**
	 * Sets the cp definition diagram entry persistence.
	 *
	 * @param cpDefinitionDiagramEntryPersistence the cp definition diagram entry persistence
	 */
	public void setCPDefinitionDiagramEntryPersistence(
		CPDefinitionDiagramEntryPersistence
			cpDefinitionDiagramEntryPersistence) {

		this.cpDefinitionDiagramEntryPersistence =
			cpDefinitionDiagramEntryPersistence;
	}

	/**
	 * Returns the cp definition diagram settings local service.
	 *
	 * @return the cp definition diagram settings local service
	 */
	public CPDefinitionDiagramSettingsLocalService
		getCPDefinitionDiagramSettingsLocalService() {

		return cpDefinitionDiagramSettingsLocalService;
	}

	/**
	 * Sets the cp definition diagram settings local service.
	 *
	 * @param cpDefinitionDiagramSettingsLocalService the cp definition diagram settings local service
	 */
	public void setCPDefinitionDiagramSettingsLocalService(
		CPDefinitionDiagramSettingsLocalService
			cpDefinitionDiagramSettingsLocalService) {

		this.cpDefinitionDiagramSettingsLocalService =
			cpDefinitionDiagramSettingsLocalService;
	}

	/**
	 * Returns the cp definition diagram settings persistence.
	 *
	 * @return the cp definition diagram settings persistence
	 */
	public CPDefinitionDiagramSettingsPersistence
		getCPDefinitionDiagramSettingsPersistence() {

		return cpDefinitionDiagramSettingsPersistence;
	}

	/**
	 * Sets the cp definition diagram settings persistence.
	 *
	 * @param cpDefinitionDiagramSettingsPersistence the cp definition diagram settings persistence
	 */
	public void setCPDefinitionDiagramSettingsPersistence(
		CPDefinitionDiagramSettingsPersistence
			cpDefinitionDiagramSettingsPersistence) {

		this.cpDefinitionDiagramSettingsPersistence =
			cpDefinitionDiagramSettingsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramSettings",
			cpDefinitionDiagramSettingsLocalService);

		_setLocalServiceUtilService(cpDefinitionDiagramSettingsLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramSettings");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CPDefinitionDiagramSettingsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CPDefinitionDiagramSettings.class;
	}

	protected String getModelClassName() {
		return CPDefinitionDiagramSettings.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				cpDefinitionDiagramSettingsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		CPDefinitionDiagramSettingsLocalService
			cpDefinitionDiagramSettingsLocalService) {

		try {
			Field field =
				CPDefinitionDiagramSettingsLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, cpDefinitionDiagramSettingsLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramEntryLocalService.class
	)
	protected com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramEntryLocalService
			cpDefinitionDiagramEntryLocalService;

	@BeanReference(type = CPDefinitionDiagramEntryPersistence.class)
	protected CPDefinitionDiagramEntryPersistence
		cpDefinitionDiagramEntryPersistence;

	@BeanReference(type = CPDefinitionDiagramSettingsLocalService.class)
	protected CPDefinitionDiagramSettingsLocalService
		cpDefinitionDiagramSettingsLocalService;

	@BeanReference(type = CPDefinitionDiagramSettingsPersistence.class)
	protected CPDefinitionDiagramSettingsPersistence
		cpDefinitionDiagramSettingsPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}