/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.shop.by.diagram.service.base;

import com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramEntry;
import com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramEntryService;
import com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramEntryServiceUtil;
import com.liferay.commerce.shop.by.diagram.service.persistence.CPDefinitionDiagramEntryPersistence;
import com.liferay.commerce.shop.by.diagram.service.persistence.CPDefinitionDiagramSettingsPersistence;
import com.liferay.expando.kernel.service.persistence.ExpandoRowPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the cp definition diagram entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.shop.by.diagram.service.impl.CPDefinitionDiagramEntryServiceImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see com.liferay.commerce.shop.by.diagram.service.impl.CPDefinitionDiagramEntryServiceImpl
 * @generated
 */
public abstract class CPDefinitionDiagramEntryServiceBaseImpl
	extends BaseServiceImpl
	implements CPDefinitionDiagramEntryService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CPDefinitionDiagramEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CPDefinitionDiagramEntryServiceUtil</code>.
	 */

	/**
	 * Returns the cp definition diagram entry local service.
	 *
	 * @return the cp definition diagram entry local service
	 */
	public com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramEntryLocalService
			getCPDefinitionDiagramEntryLocalService() {

		return cpDefinitionDiagramEntryLocalService;
	}

	/**
	 * Sets the cp definition diagram entry local service.
	 *
	 * @param cpDefinitionDiagramEntryLocalService the cp definition diagram entry local service
	 */
	public void setCPDefinitionDiagramEntryLocalService(
		com.liferay.commerce.shop.by.diagram.service.
			CPDefinitionDiagramEntryLocalService
				cpDefinitionDiagramEntryLocalService) {

		this.cpDefinitionDiagramEntryLocalService =
			cpDefinitionDiagramEntryLocalService;
	}

	/**
	 * Returns the cp definition diagram entry remote service.
	 *
	 * @return the cp definition diagram entry remote service
	 */
	public CPDefinitionDiagramEntryService
		getCPDefinitionDiagramEntryService() {

		return cpDefinitionDiagramEntryService;
	}

	/**
	 * Sets the cp definition diagram entry remote service.
	 *
	 * @param cpDefinitionDiagramEntryService the cp definition diagram entry remote service
	 */
	public void setCPDefinitionDiagramEntryService(
		CPDefinitionDiagramEntryService cpDefinitionDiagramEntryService) {

		this.cpDefinitionDiagramEntryService = cpDefinitionDiagramEntryService;
	}

	/**
	 * Returns the cp definition diagram entry persistence.
	 *
	 * @return the cp definition diagram entry persistence
	 */
	public CPDefinitionDiagramEntryPersistence
		getCPDefinitionDiagramEntryPersistence() {

		return cpDefinitionDiagramEntryPersistence;
	}

	/**
	 * Sets the cp definition diagram entry persistence.
	 *
	 * @param cpDefinitionDiagramEntryPersistence the cp definition diagram entry persistence
	 */
	public void setCPDefinitionDiagramEntryPersistence(
		CPDefinitionDiagramEntryPersistence
			cpDefinitionDiagramEntryPersistence) {

		this.cpDefinitionDiagramEntryPersistence =
			cpDefinitionDiagramEntryPersistence;
	}

	/**
	 * Returns the cp definition diagram settings local service.
	 *
	 * @return the cp definition diagram settings local service
	 */
	public com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramSettingsLocalService
			getCPDefinitionDiagramSettingsLocalService() {

		return cpDefinitionDiagramSettingsLocalService;
	}

	/**
	 * Sets the cp definition diagram settings local service.
	 *
	 * @param cpDefinitionDiagramSettingsLocalService the cp definition diagram settings local service
	 */
	public void setCPDefinitionDiagramSettingsLocalService(
		com.liferay.commerce.shop.by.diagram.service.
			CPDefinitionDiagramSettingsLocalService
				cpDefinitionDiagramSettingsLocalService) {

		this.cpDefinitionDiagramSettingsLocalService =
			cpDefinitionDiagramSettingsLocalService;
	}

	/**
	 * Returns the cp definition diagram settings remote service.
	 *
	 * @return the cp definition diagram settings remote service
	 */
	public com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramSettingsService
			getCPDefinitionDiagramSettingsService() {

		return cpDefinitionDiagramSettingsService;
	}

	/**
	 * Sets the cp definition diagram settings remote service.
	 *
	 * @param cpDefinitionDiagramSettingsService the cp definition diagram settings remote service
	 */
	public void setCPDefinitionDiagramSettingsService(
		com.liferay.commerce.shop.by.diagram.service.
			CPDefinitionDiagramSettingsService
				cpDefinitionDiagramSettingsService) {

		this.cpDefinitionDiagramSettingsService =
			cpDefinitionDiagramSettingsService;
	}

	/**
	 * Returns the cp definition diagram settings persistence.
	 *
	 * @return the cp definition diagram settings persistence
	 */
	public CPDefinitionDiagramSettingsPersistence
		getCPDefinitionDiagramSettingsPersistence() {

		return cpDefinitionDiagramSettingsPersistence;
	}

	/**
	 * Sets the cp definition diagram settings persistence.
	 *
	 * @param cpDefinitionDiagramSettingsPersistence the cp definition diagram settings persistence
	 */
	public void setCPDefinitionDiagramSettingsPersistence(
		CPDefinitionDiagramSettingsPersistence
			cpDefinitionDiagramSettingsPersistence) {

		this.cpDefinitionDiagramSettingsPersistence =
			cpDefinitionDiagramSettingsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the expando row local service.
	 *
	 * @return the expando row local service
	 */
	public com.liferay.expando.kernel.service.ExpandoRowLocalService
		getExpandoRowLocalService() {

		return expandoRowLocalService;
	}

	/**
	 * Sets the expando row local service.
	 *
	 * @param expandoRowLocalService the expando row local service
	 */
	public void setExpandoRowLocalService(
		com.liferay.expando.kernel.service.ExpandoRowLocalService
			expandoRowLocalService) {

		this.expandoRowLocalService = expandoRowLocalService;
	}

	/**
	 * Returns the expando row persistence.
	 *
	 * @return the expando row persistence
	 */
	public ExpandoRowPersistence getExpandoRowPersistence() {
		return expandoRowPersistence;
	}

	/**
	 * Sets the expando row persistence.
	 *
	 * @param expandoRowPersistence the expando row persistence
	 */
	public void setExpandoRowPersistence(
		ExpandoRowPersistence expandoRowPersistence) {

		this.expandoRowPersistence = expandoRowPersistence;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(cpDefinitionDiagramEntryService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CPDefinitionDiagramEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CPDefinitionDiagramEntry.class;
	}

	protected String getModelClassName() {
		return CPDefinitionDiagramEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				cpDefinitionDiagramEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CPDefinitionDiagramEntryService cpDefinitionDiagramEntryService) {

		try {
			Field field =
				CPDefinitionDiagramEntryServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, cpDefinitionDiagramEntryService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramEntryLocalService.class
	)
	protected com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramEntryLocalService
			cpDefinitionDiagramEntryLocalService;

	@BeanReference(type = CPDefinitionDiagramEntryService.class)
	protected CPDefinitionDiagramEntryService cpDefinitionDiagramEntryService;

	@BeanReference(type = CPDefinitionDiagramEntryPersistence.class)
	protected CPDefinitionDiagramEntryPersistence
		cpDefinitionDiagramEntryPersistence;

	@BeanReference(
		type = com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramSettingsLocalService.class
	)
	protected com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramSettingsLocalService
			cpDefinitionDiagramSettingsLocalService;

	@BeanReference(
		type = com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramSettingsService.class
	)
	protected com.liferay.commerce.shop.by.diagram.service.
		CPDefinitionDiagramSettingsService cpDefinitionDiagramSettingsService;

	@BeanReference(type = CPDefinitionDiagramSettingsPersistence.class)
	protected CPDefinitionDiagramSettingsPersistence
		cpDefinitionDiagramSettingsPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(
		type = com.liferay.expando.kernel.service.ExpandoRowLocalService.class
	)
	protected com.liferay.expando.kernel.service.ExpandoRowLocalService
		expandoRowLocalService;

	@ServiceReference(type = ExpandoRowPersistence.class)
	protected ExpandoRowPersistence expandoRowPersistence;

}